/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14.3/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation(libs.guava)
    
    // Stanford CoreNLP dependencies
    implementation("edu.stanford.nlp:stanford-corenlp:4.5.7")
    implementation("edu.stanford.nlp:stanford-corenlp:4.5.7:models")
    implementation("edu.stanford.nlp:stanford-corenlp:4.5.7:models-english")
    
    // For CSV processing
    implementation("com.opencsv:opencsv:5.9")
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit Jupiter test framework
            useJUnitJupiter("5.12.1")
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = "lab.sentiment.SentimentAnalyzer"
    applicationDefaultJvmArgs = listOf("-Xmx8g", "-Xms4g", "-XX:+UseG1GC")
}
