plugins {
    id 'java'
}

group = 'org.api'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

tasks.withType(JavaExec) {
    jvmArgs '-Dfile.encoding=UTF-8',
            '-Dstdout.encoding=UTF-8'
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}