/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;



public class AppTest {
    //@Test public void appHasAGreeting() {
       // App classUnderTest = new App();

    //}
}
