/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.neuralnet.NeuralNet;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
        NeuralNet neuralNet = new NeuralNet();

        Integer result = neuralNet.EvaluateImageFromPath("../image.png");
        if (result == null) {
            return;
        }

        System.out.printf("Модель предсказывает: %d\n", result);
        //измерение точности модели
        //neuralNet.GetStatistic();
    }
}
