/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import org.deeplearning4j.nn.multilayer.MultiLayerNetwork;

public class App {
    public static void main(String[] args) {
        try {
            MultiLayerNetwork model = CnnMNIST.trainAndEvaluate();
            System.out.println();

            String imagePath = "2.png";
            int prediction = CnnMNIST.predictFromImage(model, imagePath);
            System.out.println("Predicted digit: " + prediction);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
