/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        String inputFile = "test.txt";
        String outputFile = "res.txt";

        AssessmentProcess processor = new AssessmentProcess();
        processor.analyzeFullTextFile(inputFile, outputFile);
    }
}
