/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    public static void main(String[] args)
    {

        String inputFile;
        String outputFile;

        if (args.length >= 2)
        {
            inputFile = args[0];
            outputFile = args[1];
        }
        // For this program, if one file is specified, it is the output file
        else if (args.length == 1)
        {
            inputFile = "inputCSV.csv";
            outputFile = args[0];
        }
        else
        {
            inputFile = "inputCSV.csv";
            outputFile = "output.csv";;
        }
        try
        {
            SentimentAnalyzer sentimentAnalyzer = new SentimentAnalyzer();
            CSVProcessor csvProcessor = new CSVProcessor();

            csvProcessor.processCSV(inputFile, outputFile, sentimentAnalyzer);
            csvProcessor.checkAnalyzeSentimentResult(inputFile, outputFile);
        }
        catch (Exception e)
        {
            System.out.println("Error: " + e.getMessage());
        }
    }
}