/*
 * This source file was generated by the Gradle 'init' task
 */
package org.knn;
import java.util.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        List<Point> data = List.of(
                new Point(1, 1, "A"),
                new Point(2, 1.2, "A"),
                new Point(2.2, 2.1, "A"),
                new Point(2.5, 1.7, "A"),
                new Point(2.4, 2.6, "A"),
                new Point(2.1, 1.9, "A"),

                new Point(8, 8, "B"),
                new Point(9, 8.5, "B"),
                new Point(9.3, 9.4, "B"),
                new Point(7.7, 8.6, "B"),
                new Point(9.1, 8.8, "B"),
                new Point(7.9, 9.3, "B"),
                new Point(9.4, 8.2, "B"),

                new Point(3, 6, "C"),
                new Point(3.8, 5.5, "C"),
                new Point(4.5, 6.2, "C"),
                new Point(5, 7, "C"),
                new Point(4.2, 7.3, "C"),
                new Point(3.7, 6.8, "C"),
                new Point(4.8, 5.9, "C"),
                new Point(4.3, 7.2, "C")
        );
        double[][] testPoints = {
                {2.0, 2.0},
                {8.5, 9.0},
                {4.0, 6.5},
                {1.5, 1.5},
                {9.0, 8.0}
        };

        KNN knn = new KNN(data, 3);


        for (int i = 0; i < testPoints.length; i++) {
            double[] point = testPoints[i];
            String predicted = knn.classify(point);
            System.out.printf("Test point %d: (%.1f, %.1f) -> Classified as: %s%n",
                    i + 1, point[0], point[1], predicted);

            Point test = new Point(point[0], point[1], predicted);
            String filename = String.format("graph_%d.png", i + 1);
            Graph.save(filename, data, test, predicted);
        }
    }
}