/*
 * This file was generated by the Gradle 'init' task.
 */
plugins {
    application
}

repositories {
    mavenCentral()
}

dependencies {
    val dl4jVersion = "1.0.0-beta7"

    implementation("org.deeplearning4j:deeplearning4j-core:$dl4jVersion")
    implementation("org.nd4j:nd4j-native-platform:$dl4jVersion")
    implementation("org.deeplearning4j:deeplearning4j-datasets:$dl4jVersion")
    implementation("org.datavec:datavec-data-image:$dl4jVersion")
    implementation("ch.qos.logback:logback-classic:1.2.3")
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(11)
    }
}

application {
    mainClass = "org.example.App"
}

tasks.withType<JavaExec> {
    jvmArgs = listOf(
        "-Xmx2g",
        "--add-opens=java.base/java.lang=ALL-UNNAMED",
        "--add-opens=java.base/java.util=ALL-UNNAMED"
    )
}
